In [62]:
import pandas as pd
import numpy as np

In [63]:
df = pd.read_csv("dirty-movies.csv")
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [64]:
df['Tour title'] = df['Tour title'].replace(r'[^A-Za-z]','',regex=True)
df['Tour title'] = df['Tour title'].str.strip()
df['Tour title'] = df['Tour title'].str.title()

In [65]:
df['Artist'] = df['Artist'].replace(r'[^A-Za-z]','',regex=True)
df['Artist'] = df['Artist'].str.strip()
df['Artist'] = df['Artist'].str.title()

In [66]:
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylorswift,Theerastour,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyonc,Renaissanceworldtour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Stickysweettoura,2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautifultraumaworldtour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylorswift,Reputationstadiumtour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,Themdnatour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celinedion,Takingchancesworldtour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summercarnival,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyonc,Theformationworldtour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylorswift,Theworldtour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyonc,Themrscartershowworldtour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Ladygaga,Themonsterballtour,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katyperry,Prismaticworldtour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Livingproofthefarewelltoura,2002–2005,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessionstour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,Thetruthaboutlovetour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Ladygaga,Bornthiswayball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebelhearttour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adelelive,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylorswift,Theredtour,2013–2014,86,"$1,744,186",[26]

In [67]:
df['Year(s)'] = df['Year(s)'].str.slice(0,4)
df['Year(s)']

0     2023
1     2023
2     2008
3     2018
4     2018
5     2012
6     2008
7     2023
8     2016
9     2015
10    2013
11    2009
12    2014
13    2002
14    2006
15    2013
16    2012
17    2015
18    2016
19    2013
Name: Year(s), dtype: str

In [68]:
df.columns.tolist()

['Rank',
 'Peak',
 'All Time Peak',
 'Actual\xa0gross',
 'Adjusted\xa0gross (in 2022 dollars)',
 'Artist',
 'Tour title',
 'Year(s)',
 'Shows',
 'Average gross',
 'Ref.']

In [69]:
df = df.rename(columns={'Year(s)':'Year','Actual\xa0gross':'Actual gross','Adjusted\xa0gross (in 2022 dollars)':'Adjusted gross'})
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross,Artist,Tour title,Year,Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylorswift,Theerastour,2023,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyonc,Renaissanceworldtour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Stickysweettoura,2008,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautifultraumaworldtour,2018,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylorswift,Reputationstadiumtour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,Themdnatour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celinedion,Takingchancesworldtour,2008,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summercarnival,2023,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyonc,Theformationworldtour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylorswift,Theworldtour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyonc,Themrscartershowworldtour,2013,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Ladygaga,Themonsterballtour,2009,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katyperry,Prismaticworldtour,2014,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Livingproofthefarewelltoura,2002,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessionstour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,Thetruthaboutlovetour,2013,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Ladygaga,Bornthiswayball,2012,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebelhearttour,2015,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adelelive,2016,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylorswift,Theredtour,2013,86,"$1,744,186",[26]

In [70]:
df.columns.tolist()

['Rank',
 'Peak',
 'All Time Peak',
 'Actual gross',
 'Adjusted gross',
 'Artist',
 'Tour title',
 'Year',
 'Shows',
 'Average gross',
 'Ref.']

In [71]:
def remove_str_chars(col):
    df[col] = df[col].astype(str)
    df[col] = df[col].str.strip()
    df[col] = df[col].str.replace(r"[^0-9.]", "", regex=True)

numeric_columns = ['Actual gross','Adjusted gross', 'Average gross', 'Peak','All Time Peak']

for col in numeric_columns:
    if not col in df.columns.tolist():
        raise KeyError(f"{col} not found")
    remove_str_chars(col)
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross,Artist,Tour title,Year,Shows,Average gross,Ref.
0,1,1,2,780000000,780000000,Taylorswift,Theerastour,2023,56,13928571,[1]
1,2,1,72,579800000,579800000,Beyonc,Renaissanceworldtour,2023,56,10353571,[3]
2,3,14,25,411000000,560622615,Madonna,Stickysweettoura,2008,85,4835294,[6]
3,4,27,107,397300000,454751555,Pink,Beautifultraumaworldtour,2018,156,2546795,[7]
4,5,24,NaN,345675146,402844849,Taylorswift,Reputationstadiumtour,2018,53,6522173,[8]
5,6,24,109,305158363,388978496,Madonna,Themdnatour,2012,88,3467709,[9]
6,7,210,NaN,280000000,381932682,Celinedion,Takingchancesworldtour,2008,131,2137405,[11]
7,7,NaN,NaN,257600000,257600000,Pink,Summercarnival,2023,41,6282927,[12]
8,9,NaN,NaN,256084556,312258401,Beyonc,Theformationworldtour,2016,49,5226215,[13]
9,10,NaN,NaN,250400000,309141878,Taylorswift,Theworldtour,2015,85,2945882,[14]
10,11,NaN,NaN,229100000,283202896,Beyonc,Themrscartershowworldtour,2013,132,1735606,[15][16]
11,12,NaN,1417,227400000,295301479,Ladygaga,Themonsterballtour,2009,203,1118227,[18]
12,13,NaN,NaN,204000000,251856802,Katyperry,Prismaticworldtour,2014,151,1350993,[19]
13,14,120,NaN,200000000,299676265,Cher,Livingproofthefarewelltoura,2002,325,615385,[20]
14,15,2,NaN,194000000,281617035,Madonna,Confessionstour,2006,60,3233333,[5]
15,16,NaN,NaN,184000000,227452347,Pink,Thetruthaboutlovetour,2013,142,1295775,[22]
16,17,NaN,NaN,170000000,213568571,Ladygaga,Bornthiswayball,2012,98,1734694,[d]
17,18,NaN,NaN,169800000,207046755,Madonna,Rebelhearttour,2015,82,2070732,[4]
18,19,NaN,NaN,167700000,204486106,Adele,Adelelive,2016,121,1385950,[25]
19,20,NaN,NaN,150000000,185423109,Taylorswift,Theredtour,2013,86,1744186,[26]

In [72]:
def to_numeric(col):
    df[col] = pd.to_numeric(df[col],errors="coerce")

for col in numeric_columns:
    if not col in df.columns.tolist():
        raise KeyError(f"{col} not found")
    to_numeric(col)

df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross,Artist,Tour title,Year,Shows,Average gross,Ref.
0,1,1.0,2.0,780000000,780000000,Taylorswift,Theerastour,2023,56,13928571,[1]
1,2,1.0,72.0,579800000,579800000,Beyonc,Renaissanceworldtour,2023,56,10353571,[3]
2,3,14.0,25.0,411000000,560622615,Madonna,Stickysweettoura,2008,85,4835294,[6]
3,4,27.0,107.0,397300000,454751555,Pink,Beautifultraumaworldtour,2018,156,2546795,[7]
4,5,24.0,NaN,345675146,402844849,Taylorswift,Reputationstadiumtour,2018,53,6522173,[8]
5,6,24.0,109.0,305158363,388978496,Madonna,Themdnatour,2012,88,3467709,[9]
6,7,210.0,NaN,280000000,381932682,Celinedion,Takingchancesworldtour,2008,131,2137405,[11]
7,7,NaN,NaN,257600000,257600000,Pink,Summercarnival,2023,41,6282927,[12]
8,9,NaN,NaN,256084556,312258401,Beyonc,Theformationworldtour,2016,49,5226215,[13]
9,10,NaN,NaN,250400000,309141878,Taylorswift,Theworldtour,2015,85,2945882,[14]
10,11,NaN,NaN,229100000,283202896,Beyonc,Themrscartershowworldtour,2013,132,1735606,[15][16]
11,12,NaN,1417.0,227400000,295301479,Ladygaga,Themonsterballtour,2009,203,1118227,[18]
12,13,NaN,NaN,204000000,251856802,Katyperry,Prismaticworldtour,2014,151,1350993,[19]
13,14,120.0,NaN,200000000,299676265,Cher,Livingproofthefarewelltoura,2002,325,615385,[20]
14,15,2.0,NaN,194000000,281617035,Madonna,Confessionstour,2006,60,3233333,[5]
15,16,NaN,NaN,184000000,227452347,Pink,Thetruthaboutlovetour,2013,142,1295775,[22]
16,17,NaN,NaN,170000000,213568571,Ladygaga,Bornthiswayball,2012,98,1734694,[d]
17,18,NaN,NaN,169800000,207046755,Madonna,Rebelhearttour,2015,82,2070732,[4]
18,19,NaN,NaN,167700000,204486106,Adele,Adelelive,2016,121,1385950,[25]
19,20,NaN,NaN,150000000,185423109,Taylorswift,Theredtour,2013,86,1744186,[26]

In [73]:
df = df.drop(columns=['Ref.'])

In [74]:
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross,Artist,Tour title,Year,Shows,Average gross
0,1,1.0,2.0,780000000,780000000,Taylorswift,Theerastour,2023,56,13928571
1,2,1.0,72.0,579800000,579800000,Beyonc,Renaissanceworldtour,2023,56,10353571
2,3,14.0,25.0,411000000,560622615,Madonna,Stickysweettoura,2008,85,4835294
3,4,27.0,107.0,397300000,454751555,Pink,Beautifultraumaworldtour,2018,156,2546795
4,5,24.0,NaN,345675146,402844849,Taylorswift,Reputationstadiumtour,2018,53,6522173
5,6,24.0,109.0,305158363,388978496,Madonna,Themdnatour,2012,88,3467709
6,7,210.0,NaN,280000000,381932682,Celinedion,Takingchancesworldtour,2008,131,2137405
7,7,NaN,NaN,257600000,257600000,Pink,Summercarnival,2023,41,6282927
8,9,NaN,NaN,256084556,312258401,Beyonc,Theformationworldtour,2016,49,5226215
9,10,NaN,NaN,250400000,309141878,Taylorswift,Theworldtour,2015,85,2945882
10,11,NaN,NaN,229100000,283202896,Beyonc,Themrscartershowworldtour,2013,132,1735606
11,12,NaN,1417.0,227400000,295301479,Ladygaga,Themonsterballtour,2009,203,1118227
12,13,NaN,NaN,204000000,251856802,Katyperry,Prismaticworldtour,2014,151,1350993
13,14,120.0,NaN,200000000,299676265,Cher,Livingproofthefarewelltoura,2002,325,615385
14,15,2.0,NaN,194000000,281617035,Madonna,Confessionstour,2006,60,3233333
15,16,NaN,NaN,184000000,227452347,Pink,Thetruthaboutlovetour,2013,142,1295775
16,17,NaN,NaN,170000000,213568571,Ladygaga,Bornthiswayball,2012,98,1734694
17,18,NaN,NaN,169800000,207046755,Madonna,Rebelhearttour,2015,82,2070732
18,19,NaN,NaN,167700000,204486106,Adele,Adelelive,2016,121,1385950
19,20,NaN,NaN,150000000,185423109,Taylorswift,Theredtour,2013,86,1744186

In [75]:
df.isna().sum()

Rank               0
Peak              11
All Time Peak     14
Actual gross       0
Adjusted gross     0
Artist             0
Tour title         0
Year               0
Shows              0
Average gross      0
dtype: int64

In [76]:
df[['Peak','All Time Peak']] = df[['Peak','All Time Peak']].interpolate()
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross,Artist,Tour title,Year,Shows,Average gross
0,1,1.000000,2.0,780000000,780000000,Taylorswift,Theerastour,2023,56,13928571
1,2,1.000000,72.0,579800000,579800000,Beyonc,Renaissanceworldtour,2023,56,10353571
2,3,14.000000,25.0,411000000,560622615,Madonna,Stickysweettoura,2008,85,4835294
3,4,27.000000,107.0,397300000,454751555,Pink,Beautifultraumaworldtour,2018,156,2546795
4,5,24.000000,108.0,345675146,402844849,Taylorswift,Reputationstadiumtour,2018,53,6522173
5,6,24.000000,109.0,305158363,388978496,Madonna,Themdnatour,2012,88,3467709
6,7,210.000000,327.0,280000000,381932682,Celinedion,Takingchancesworldtour,2008,131,2137405
7,7,197.142857,545.0,257600000,257600000,Pink,Summercarnival,2023,41,6282927
8,9,184.285714,763.0,256084556,312258401,Beyonc,Theformationworldtour,2016,49,5226215
9,10,171.428571,981.0,250400000,309141878,Taylorswift,Theworldtour,2015,85,2945882
10,11,158.571429,1199.0,229100000,283202896,Beyonc,Themrscartershowworldtour,2013,132,1735606
11,12,145.714286,1417.0,227400000,295301479,Ladygaga,Themonsterballtour,2009,203,1118227
12,13,132.857143,1417.0,204000000,251856802,Katyperry,Prismaticworldtour,2014,151,1350993
13,14,120.000000,1417.0,200000000,299676265,Cher,Livingproofthefarewelltoura,2002,325,615385
14,15,2.000000,1417.0,194000000,281617035,Madonna,Confessionstour,2006,60,3233333
15,16,2.000000,1417.0,184000000,227452347,Pink,Thetruthaboutlovetour,2013,142,1295775
16,17,2.000000,1417.0,170000000,213568571,Ladygaga,Bornthiswayball,2012,98,1734694
17,18,2.000000,1417.0,169800000,207046755,Madonna,Rebelhearttour,2015,82,2070732
18,19,2.000000,1417.0,167700000,204486106,Adele,Adelelive,2016,121,1385950
19,20,2.000000,1417.0,150000000,185423109,Taylorswift,Theredtour,2013,86,1744186

In [77]:
df.to_csv("clean_movies.csv")