In [90]:
import pandas as pd

In [91]:
pd.__version__

'3.0.3'

In [92]:
data = {
    "name":["ahmed","john","faduma"],
    "age":[33,54,18],
}
dataset = pd.DataFrame(data)
dataset

     name  age
0   ahmed   33
1    john   54
2  faduma   18

In [93]:
print(dataset.shape)
print(dataset['age'].mean())
print(dataset['age'].max())
print(dataset['age'].std())

(3, 2)
35.0
54
18.083141320025124

In [94]:
dataset.describe()

             age
count   3.000000
mean   35.000000
std    18.083141
min    18.000000
25%    25.500000
50%    33.000000
75%    43.500000
max    54.000000

In [95]:
dataset[dataset['age'] > 20] # conditional select

    name  age
0  ahmed   33
1   john   54

In [96]:
df = pd.read_csv('weather.csv')
df.head(2)

         date       city  temperature_c  humidity wind_speed  rainfall_mm
0  2026-01-01  Mogadishu           31.0      75.0         12          0.0
1  2026-01-02  Mogadishu           32.0      78.0        NaN          0.0

In [97]:
df.tail(3)

         date       city  temperature_c  humidity wind_speed  rainfall_mm
7  2026-01-08     Afgoye            NaN      79.0         11          0.0
8  2026-01-09     Balcad           30.0      76.0         10          NaN
9  2026-01-10  Mogadishu           29.0      74.0          9          0.0

In [98]:
df['temperature_c'].max()

np.float64(35.0)

In [99]:
df[df['rainfall_mm'] > 0]

         date       city  temperature_c  humidity wind_speed  rainfall_mm
2  2026-01-03    Kismayo            NaN      80.0         15          1.0
5  2026-01-06  Mogadishu           33.0       NaN         13          2.0

In [100]:
df[df['humidity'] > df['humidity'].mean()]

         date       city  temperature_c  humidity wind_speed  rainfall_mm
2  2026-01-03    Kismayo            NaN      80.0         15          1.0
3  2026-01-04  Mogadishu           34.0      82.0         14          0.0
4  2026-01-05     Jowhar           35.0      85.0         16          0.0
7  2026-01-08     Afgoye            NaN      79.0         11          0.0

In [101]:
type(df['date'])

pandas.Series

In [102]:
df[df['date'] >= '2026-01-04']

         date       city  temperature_c  humidity wind_speed  rainfall_mm
3  2026-01-04  Mogadishu           34.0      82.0         14          0.0
4  2026-01-05     Jowhar           35.0      85.0         16          0.0
5  2026-01-06  Mogadishu           33.0       NaN         13          2.0
6  2026-01-07    Kismayo           31.0      77.0        abc          0.0
7  2026-01-08     Afgoye            NaN      79.0         11          0.0
8  2026-01-09     Balcad           30.0      76.0         10          NaN
9  2026-01-10  Mogadishu           29.0      74.0          9          0.0

In [103]:
df[df['city'] == 'Kismayo']

         date     city  temperature_c  humidity wind_speed  rainfall_mm
2  2026-01-03  Kismayo            NaN      80.0         15          1.0
6  2026-01-07  Kismayo           31.0      77.0        abc          0.0

In [104]:
df[df['wind_speed'] > df['wind_speed'].min()]

         date       city  temperature_c  humidity wind_speed  rainfall_mm
0  2026-01-01  Mogadishu           31.0      75.0         12          0.0
2  2026-01-03    Kismayo            NaN      80.0         15          1.0
3  2026-01-04  Mogadishu           34.0      82.0         14          0.0
4  2026-01-05     Jowhar           35.0      85.0         16          0.0
5  2026-01-06  Mogadishu           33.0       NaN         13          2.0
6  2026-01-07    Kismayo           31.0      77.0        abc          0.0
7  2026-01-08     Afgoye            NaN      79.0         11          0.0
9  2026-01-10  Mogadishu           29.0      74.0          9          0.0

# Conditional selection
- condition_mask is the where condition like in sql
- columns is like select with specified columns in sql
- in sql mind looks like  select date,city,temperature_c from df where temperature_c > 22
- what about * all columns just remove columns

In [105]:
condition_mask = df['temperature_c'] > 22
columns = ['date','city','temperature_c']
print(df[condition_mask])
df[columns][condition_mask]

         date       city  temperature_c  humidity wind_speed  rainfall_mm
0  2026-01-01  Mogadishu           31.0      75.0         12          0.0
1  2026-01-02  Mogadishu           32.0      78.0        NaN          0.0
3  2026-01-04  Mogadishu           34.0      82.0         14          0.0
4  2026-01-05     Jowhar           35.0      85.0         16          0.0
5  2026-01-06  Mogadishu           33.0       NaN         13          2.0
6  2026-01-07    Kismayo           31.0      77.0        abc          0.0
8  2026-01-09     Balcad           30.0      76.0         10          NaN
9  2026-01-10  Mogadishu           29.0      74.0          9          0.0

         date       city  temperature_c
0  2026-01-01  Mogadishu           31.0
1  2026-01-02  Mogadishu           32.0
3  2026-01-04  Mogadishu           34.0
4  2026-01-05     Jowhar           35.0
5  2026-01-06  Mogadishu           33.0
6  2026-01-07    Kismayo           31.0
8  2026-01-09     Balcad           30.0
9  2026-01-10  Mogadishu           29.0