In [971]:
import pandas as pd

In [972]:
pd.__version__

'3.0.3'

In [973]:
data = {
    "name":["ahmed","john","faduma"],
    "age":[33,54,18],
}
dataset = pd.DataFrame(data)
dataset

     name  age
0   ahmed   33
1    john   54
2  faduma   18

In [974]:
print(dataset.shape)
print(dataset['age'].mean())
print(dataset['age'].max())
print(dataset['age'].std())

(3, 2)
35.0
54
18.083141320025124

In [975]:
dataset.describe()

             age
count   3.000000
mean   35.000000
std    18.083141
min    18.000000
25%    25.500000
50%    33.000000
75%    43.500000
max    54.000000

In [976]:
dataset[dataset['age'] > 20] # conditional select

    name  age
0  ahmed   33
1   john   54

In [977]:
df = pd.read_csv('weather.csv')
df.head(2)

,date,city,temperature_c,humidity,wind_speed,rainfall_mm
0,2026-01-01,mogadishu,31.0,75.0,12,0.0
1,2026-01-02,mogadishu,32.0,78.0,NaN,0.0

In [978]:
df.tail(3)

         date       city  temperature_c  humidity wind_speed  rainfall_mm
7  2026-01-08     afgoye            NaN      79.0         11          0.0
8  2026-01-09     Balcad           30.0      76.0         10          NaN
9  2026-01-10  Mogadishu           29.0      74.0          9          0.0

In [979]:
df['temperature_c'].max()

np.float64(35.0)

In [980]:
df[df['rainfall_mm'] > 0]

         date       city  temperature_c  humidity wind_speed  rainfall_mm
2  2026-01-03    kismayo            NaN      80.0         15          1.0
5  2026-01-06  Mogadishu           33.0       NaN         13          2.0

In [981]:
df[df['humidity'] > df['humidity'].mean()]

         date       city  temperature_c  humidity wind_speed  rainfall_mm
2  2026-01-03    kismayo            NaN      80.0         15          1.0
3  2026-01-04  Mogadishu           34.0      82.0         14          0.0
4  2026-01-05     Jowhar           35.0      85.0         16          0.0
7  2026-01-08     afgoye            NaN      79.0         11          0.0

In [982]:
type(df['date'])

pandas.Series

In [983]:
df[df['date'] >= '2026-01-04']

         date       city  temperature_c  humidity wind_speed  rainfall_mm
3  2026-01-04  Mogadishu           34.0      82.0         14          0.0
4  2026-01-05     Jowhar           35.0      85.0         16          0.0
5  2026-01-06  Mogadishu           33.0       NaN         13          2.0
6  2026-01-07    Kismayo           31.0      77.0        abc          0.0
7  2026-01-08     afgoye            NaN      79.0         11          0.0
8  2026-01-09     Balcad           30.0      76.0         10          NaN
9  2026-01-10  Mogadishu           29.0      74.0          9          0.0

In [984]:
df[df['city'] == 'Kismayo']

         date     city  temperature_c  humidity wind_speed  rainfall_mm
6  2026-01-07  Kismayo           31.0      77.0        abc          0.0

In [985]:
df[df['wind_speed'] > df['wind_speed'].min()]

,date,city,temperature_c,humidity,wind_speed,rainfall_mm
0,2026-01-01,mogadishu,31.0,75.0,12,0.0
2,2026-01-03,kismayo,NaN,80.0,15,1.0
3,2026-01-04,Mogadishu,34.0,82.0,14,0.0
4,2026-01-05,Jowhar,35.0,85.0,16,0.0
5,2026-01-06,Mogadishu,33.0,NaN,13,2.0
6,2026-01-07,Kismayo,31.0,77.0,abc,0.0
7,2026-01-08,afgoye,NaN,79.0,11,0.0
9,2026-01-10,Mogadishu,29.0,74.0,9,0.0

# Conditional selection
- condition_mask is the where condition like in sql
- columns is like select with specified columns in sql
- in sql mind looks like  select date,city,temperature_c from df where temperature_c > 22
- what about * all columns just remove columns

In [986]:
condition_mask = df['temperature_c'] > 22
columns = ['date','city','temperature_c']
print(df[condition_mask])
df[columns][condition_mask]

         date                   city  temperature_c  humidity wind_speed  \
0  2026-01-01  mogadishu                       31.0      75.0         12
1  2026-01-02              mogadishu           32.0      78.0        NaN
3  2026-01-04              Mogadishu           34.0      82.0         14
4  2026-01-05                 Jowhar           35.0      85.0         16
5  2026-01-06              Mogadishu           33.0       NaN         13
6  2026-01-07                Kismayo           31.0      77.0        abc
8  2026-01-09                 Balcad           30.0      76.0         10
9  2026-01-10              Mogadishu           29.0      74.0          9

   rainfall_mm
0          0.0
1          0.0
3          0.0
4          0.0
5          2.0
6          0.0
8          NaN
9          0.0

         date                   city  temperature_c
0  2026-01-01  mogadishu                       31.0
1  2026-01-02              mogadishu           32.0
3  2026-01-04              Mogadishu           34.0
4  2026-01-05                 Jowhar           35.0
5  2026-01-06              Mogadishu           33.0
6  2026-01-07                Kismayo           31.0
8  2026-01-09                 Balcad           30.0
9  2026-01-10              Mogadishu           29.0

In [987]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [988]:
df.set_index('date',inplace=True)

In [989]:
df

,city,temperature_c,humidity,wind_speed,rainfall_mm
date,,,,,
2026-01-01,mogadishu,31.0,75.0,12,0.0
2026-01-02,mogadishu,32.0,78.0,NaN,0.0
2026-01-03,kismayo,NaN,80.0,15,1.0
2026-01-04,Mogadishu,34.0,82.0,14,0.0
2026-01-05,Jowhar,35.0,85.0,16,0.0
2026-01-06,Mogadishu,33.0,NaN,13,2.0
2026-01-07,Kismayo,31.0,77.0,abc,0.0
2026-01-08,afgoye,NaN,79.0,11,0.0
2026-01-09,Balcad,30.0,76.0,10,NaN
2026-01-10,Mogadishu,29.0,74.0,9,0.0

In [990]:
df.loc['2026-01-01']

city             mogadishu
temperature_c                     31.0
humidity                          75.0
wind_speed                          12
rainfall_mm                        0.0
Name: 2026-01-01, dtype: object

In [991]:
df.reset_index(inplace=True)

In [992]:
df

,date,city,temperature_c,humidity,wind_speed,rainfall_mm
0,2026-01-01,mogadishu,31.0,75.0,12,0.0
1,2026-01-02,mogadishu,32.0,78.0,NaN,0.0
2,2026-01-03,kismayo,NaN,80.0,15,1.0
3,2026-01-04,Mogadishu,34.0,82.0,14,0.0
4,2026-01-05,Jowhar,35.0,85.0,16,0.0
5,2026-01-06,Mogadishu,33.0,NaN,13,2.0
6,2026-01-07,Kismayo,31.0,77.0,abc,0.0
7,2026-01-08,afgoye,NaN,79.0,11,0.0
8,2026-01-09,Balcad,30.0,76.0,10,NaN
9,2026-01-10,Mogadishu,29.0,74.0,9,0.0

In [993]:
df.loc[0]

date                        2026-01-01
city             mogadishu
temperature_c                     31.0
humidity                          75.0
wind_speed                          12
rainfall_mm                        0.0
Name: 0, dtype: object

In [994]:
df.loc[[1,2]]

         date       city  temperature_c  humidity wind_speed  rainfall_mm
1  2026-01-02  mogadishu           32.0      78.0        NaN          0.0
2  2026-01-03    kismayo            NaN      80.0         15          1.0

## Locating with Series and DataFrame using df.loc

In [995]:
# Series
df.loc[1]

date             2026-01-02
city              mogadishu
temperature_c          32.0
humidity               78.0
wind_speed              NaN
rainfall_mm             0.0
Name: 1, dtype: object

In [996]:
# DataFrame
df.loc[[1,2]]

         date       city  temperature_c  humidity wind_speed  rainfall_mm
1  2026-01-02  mogadishu           32.0      78.0        NaN          0.0
2  2026-01-03    kismayo            NaN      80.0         15          1.0

# Ways to create DataFrame

In [997]:
# csv
df = pd.read_csv("weather.csv")
df

,date,city,temperature_c,humidity,wind_speed,rainfall_mm
0,2026-01-01,mogadishu,31.0,75.0,12,0.0
1,2026-01-02,mogadishu,32.0,78.0,NaN,0.0
2,2026-01-03,kismayo,NaN,80.0,15,1.0
3,2026-01-04,Mogadishu,34.0,82.0,14,0.0
4,2026-01-05,Jowhar,35.0,85.0,16,0.0
5,2026-01-06,Mogadishu,33.0,NaN,13,2.0
6,2026-01-07,Kismayo,31.0,77.0,abc,0.0
7,2026-01-08,afgoye,NaN,79.0,11,0.0
8,2026-01-09,Balcad,30.0,76.0,10,NaN
9,2026-01-10,Mogadishu,29.0,74.0,9,0.0

In [998]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           10 non-null     str
 1   city           10 non-null     str
 2   temperature_c  8 non-null      float64
 3   humidity       9 non-null      float64
 4   wind_speed     9 non-null      str
 5   rainfall_mm    9 non-null      float64
dtypes: float64(3), str(3)
memory usage: 612.0 bytes

In [999]:
# dictionary
weather_data = {
    "date":['2026-01-03','2025-10-23'],
    "city":["mogadishu","Kismayo"],
    "temperature":[31,28]
}

df = pd.DataFrame(weather_data)
df

         date       city  temperature
0  2026-01-03  mogadishu           31
1  2025-10-23    Kismayo           28

In [1000]:
# tuple list
weather_data = {
    ('2026-01-08','mogadishu',29),
    ('2025-09-11','jowhar',28)
}

df = pd.DataFrame(weather_data,columns=['date','city','temperature'])
df

         date       city  temperature
0  2026-01-08  mogadishu           29
1  2025-09-11     jowhar           28

In [1001]:
# dictionary list
weather_data = [
    {'city':'mogadishu','temperature':22},
    {'city':'london','temperature':18},
    {'city':'paris','temperature':23}
]

df = pd.DataFrame(weather_data)
df

        city  temperature
0  mogadishu           22
1     london           18
2      paris           23

In [1002]:
# excel
df = pd.read_excel("weather.xlsx",sheet_name="Sheet1")
df

,Unnamed: 0,date,city,temperature_c,humidity,wind_speed,rainfall_mm
0,0,2026-01-01,Mogadishu,31.0,75.0,12,0.0
1,1,2026-01-02,Mogadishu,32.0,78.0,NaN,0.0
2,2,2026-01-03,Kismayo,NaN,80.0,15,1.0
3,3,2026-01-04,Mogadishu,34.0,82.0,14,0.0
4,4,2026-01-05,Jowhar,35.0,85.0,16,0.0
5,5,2026-01-06,Mogadishu,33.0,NaN,13,2.0
6,6,2026-01-07,Kismayo,31.0,77.0,abc,0.0
7,7,2026-01-08,Afgoye,NaN,79.0,11,0.0
8,8,2026-01-09,Balcad,30.0,76.0,10,NaN
9,9,2026-01-10,Mogadishu,29.0,74.0,9,0.0

In [1003]:
# Json
df = pd.read_json("weather.json")
df

        city  temperature
0  mogadishu           27
1    kismayo           21
2     jowhar           29

In [1004]:
df.describe()

       temperature
count     3.000000
mean     25.666667
std       4.163332
min      21.000000
25%      24.000000
50%      27.000000
75%      28.000000
max      29.000000

In [1005]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   city         3 non-null      str
 1   temperature  3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [1006]:
df[["city","temperature"]]

        city  temperature
0  mogadishu           27
1    kismayo           21
2     jowhar           29

In [1007]:
df["city"]

0    mogadishu
1      kismayo
2       jowhar
Name: city, dtype: str

## Filtering

In [1008]:
df = pd.read_csv("weather.csv")
df

,date,city,temperature_c,humidity,wind_speed,rainfall_mm
0,2026-01-01,mogadishu,31.0,75.0,12,0.0
1,2026-01-02,mogadishu,32.0,78.0,NaN,0.0
2,2026-01-03,kismayo,NaN,80.0,15,1.0
3,2026-01-04,Mogadishu,34.0,82.0,14,0.0
4,2026-01-05,Jowhar,35.0,85.0,16,0.0
5,2026-01-06,Mogadishu,33.0,NaN,13,2.0
6,2026-01-07,Kismayo,31.0,77.0,abc,0.0
7,2026-01-08,afgoye,NaN,79.0,11,0.0
8,2026-01-09,Balcad,30.0,76.0,10,NaN
9,2026-01-10,Mogadishu,29.0,74.0,9,0.0

In [1009]:
df[df['temperature_c'] > 23]

,date,city,temperature_c,humidity,wind_speed,rainfall_mm
0,2026-01-01,mogadishu,31.0,75.0,12,0.0
1,2026-01-02,mogadishu,32.0,78.0,NaN,0.0
3,2026-01-04,Mogadishu,34.0,82.0,14,0.0
4,2026-01-05,Jowhar,35.0,85.0,16,0.0
5,2026-01-06,Mogadishu,33.0,NaN,13,2.0
6,2026-01-07,Kismayo,31.0,77.0,abc,0.0
8,2026-01-09,Balcad,30.0,76.0,10,NaN
9,2026-01-10,Mogadishu,29.0,74.0,9,0.0

In [1010]:
condition_mask = (df['temperature_c'] > 23 ) & (df['city'] == "Mogadishu")
df[condition_mask]

         date       city  temperature_c  humidity wind_speed  rainfall_mm
3  2026-01-04  Mogadishu           34.0      82.0         14          0.0
5  2026-01-06  Mogadishu           33.0       NaN         13          2.0
9  2026-01-10  Mogadishu           29.0      74.0          9          0.0

In [1011]:
df[(df['humidity'] > 18) & (df['rainfall_mm'] > 0)]

         date     city  temperature_c  humidity wind_speed  rainfall_mm
2  2026-01-03  kismayo            NaN      80.0         15          1.0

In [1012]:
mask = (df['temperature_c'] < 30) | (df['rainfall_mm'] > 0)
df[mask]

         date       city  temperature_c  humidity wind_speed  rainfall_mm
2  2026-01-03    kismayo            NaN      80.0         15          1.0
5  2026-01-06  Mogadishu           33.0       NaN         13          2.0
9  2026-01-10  Mogadishu           29.0      74.0          9          0.0

In [1013]:
df = pd.read_csv("weather.csv")
df

,date,city,temperature_c,humidity,wind_speed,rainfall_mm
0,2026-01-01,mogadishu,31.0,75.0,12,0.0
1,2026-01-02,mogadishu,32.0,78.0,NaN,0.0
2,2026-01-03,kismayo,NaN,80.0,15,1.0
3,2026-01-04,Mogadishu,34.0,82.0,14,0.0
4,2026-01-05,Jowhar,35.0,85.0,16,0.0
5,2026-01-06,Mogadishu,33.0,NaN,13,2.0
6,2026-01-07,Kismayo,31.0,77.0,abc,0.0
7,2026-01-08,afgoye,NaN,79.0,11,0.0
8,2026-01-09,Balcad,30.0,76.0,10,NaN
9,2026-01-10,Mogadishu,29.0,74.0,9,0.0

In [1014]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           10 non-null     str
 1   city           10 non-null     str
 2   temperature_c  8 non-null      float64
 3   humidity       9 non-null      float64
 4   wind_speed     9 non-null      str
 5   rainfall_mm    9 non-null      float64
dtypes: float64(3), str(3)
memory usage: 612.0 bytes

In [1015]:
df.describe()

       temperature_c   humidity  rainfall_mm
count        8.00000   9.000000     9.000000
mean        31.87500  78.444444     0.333333
std          2.03101   3.503966     0.707107
min         29.00000  74.000000     0.000000
25%         30.75000  76.000000     0.000000
50%         31.50000  78.000000     0.000000
75%         33.25000  80.000000     0.000000
max         35.00000  85.000000     2.000000

In [1016]:
df.shape

(10, 6)

In [1017]:
df.columns

Index(['date', 'city', 'temperature_c', 'humidity', 'wind_speed',
       'rainfall_mm'],
      dtype='str')

In [1018]:
df.isna().sum()

date             0
city             0
temperature_c    2
humidity         1
wind_speed       1
rainfall_mm      1
dtype: int64

In [1019]:
def stander_name(col):
    df[col] = df[col].astype(str).str.strip()
    df[col] = df[col].astype(str).str.title()

stander_name('city')
df

         date       city  temperature_c  humidity wind_speed  rainfall_mm
0  2026-01-01  Mogadishu           31.0      75.0         12          0.0
1  2026-01-02  Mogadishu           32.0      78.0        NaN          0.0
2  2026-01-03    Kismayo            NaN      80.0         15          1.0
3  2026-01-04  Mogadishu           34.0      82.0         14          0.0
4  2026-01-05     Jowhar           35.0      85.0         16          0.0
5  2026-01-06  Mogadishu           33.0       NaN         13          2.0
6  2026-01-07    Kismayo           31.0      77.0        abc          0.0
7  2026-01-08     Afgoye            NaN      79.0         11          0.0
8  2026-01-09     Balcad           30.0      76.0         10          NaN
9  2026-01-10  Mogadishu           29.0      74.0          9          0.0

In [1020]:
def numeric_fix(col):
    df[col] = pd.to_numeric(df[col],errors="coerce")

numeric_fix('temperature_c')
numeric_fix('humidity')
numeric_fix('wind_speed')
numeric_fix('rainfall_mm')
df

         date       city  temperature_c  humidity  wind_speed  rainfall_mm
0  2026-01-01  Mogadishu           31.0      75.0        12.0          0.0
1  2026-01-02  Mogadishu           32.0      78.0         NaN          0.0
2  2026-01-03    Kismayo            NaN      80.0        15.0          1.0
3  2026-01-04  Mogadishu           34.0      82.0        14.0          0.0
4  2026-01-05     Jowhar           35.0      85.0        16.0          0.0
5  2026-01-06  Mogadishu           33.0       NaN        13.0          2.0
6  2026-01-07    Kismayo           31.0      77.0         NaN          0.0
7  2026-01-08     Afgoye            NaN      79.0        11.0          0.0
8  2026-01-09     Balcad           30.0      76.0        10.0          NaN
9  2026-01-10  Mogadishu           29.0      74.0         9.0          0.0

In [1021]:
df.isna().sum()

date             0
city             0
temperature_c    2
humidity         1
wind_speed       2
rainfall_mm      1
dtype: int64

In [1022]:
def fill_none(col):
    df.fillna({ col: df[col].median() },inplace=True)

fill_none('humidity')
fill_none('temperature_c')
fill_none('wind_speed')
fill_none('rainfall_mm')

df

         date       city  temperature_c  humidity  wind_speed  rainfall_mm
0  2026-01-01  Mogadishu           31.0      75.0        12.0          0.0
1  2026-01-02  Mogadishu           32.0      78.0        12.5          0.0
2  2026-01-03    Kismayo           31.5      80.0        15.0          1.0
3  2026-01-04  Mogadishu           34.0      82.0        14.0          0.0
4  2026-01-05     Jowhar           35.0      85.0        16.0          0.0
5  2026-01-06  Mogadishu           33.0      78.0        13.0          2.0
6  2026-01-07    Kismayo           31.0      77.0        12.5          0.0
7  2026-01-08     Afgoye           31.5      79.0        11.0          0.0
8  2026-01-09     Balcad           30.0      76.0        10.0          0.0
9  2026-01-10  Mogadishu           29.0      74.0         9.0          0.0

In [1023]:
# fix target value to 0 or 1
# df['rainfall_mm'][df['rainfall_mm'] > 1] = 1 # raise ChainedAssignmentError.

[ChainedAssignmentError Pandas Docs](https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment)

In [1024]:
# this works 
df.loc[df['rainfall_mm']>1,'rainfall_mm'] = 1
df

         date       city  temperature_c  humidity  wind_speed  rainfall_mm
0  2026-01-01  Mogadishu           31.0      75.0        12.0          0.0
1  2026-01-02  Mogadishu           32.0      78.0        12.5          0.0
2  2026-01-03    Kismayo           31.5      80.0        15.0          1.0
3  2026-01-04  Mogadishu           34.0      82.0        14.0          0.0
4  2026-01-05     Jowhar           35.0      85.0        16.0          0.0
5  2026-01-06  Mogadishu           33.0      78.0        13.0          1.0
6  2026-01-07    Kismayo           31.0      77.0        12.5          0.0
7  2026-01-08     Afgoye           31.5      79.0        11.0          0.0
8  2026-01-09     Balcad           30.0      76.0        10.0          0.0
9  2026-01-10  Mogadishu           29.0      74.0         9.0          0.0

In [1025]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           10 non-null     str
 1   city           10 non-null     str
 2   temperature_c  10 non-null     float64
 3   humidity       10 non-null     float64
 4   wind_speed     10 non-null     float64
 5   rainfall_mm    10 non-null     float64
dtypes: float64(4), str(2)
memory usage: 612.0 bytes

In [1026]:
df.isna().sum()

date             0
city             0
temperature_c    0
humidity         0
wind_speed       0
rainfall_mm      0
dtype: int64

In [ ]:
# convert to categorical because of it repeats 0 and 1. 
df['rainfall_mm'] = df['rainfall_mm'].astype('category')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           10 non-null     str
 1   city           10 non-null     str
 2   temperature_c  10 non-null     float64
 3   humidity       10 non-null     float64
 4   wind_speed     10 non-null     float64
 5   rainfall_mm    10 non-null     category
dtypes: category(1), float64(3), str(2)
memory usage: 558.0 bytes

In [1029]:
df.to_csv("clean_weather.csv")