In [52]:
import pandas as pd

In [53]:
pd.__version__

'3.0.3'

In [54]:
data = {
    "name":["ahmed","john","faduma"],
    "age":[33,54,18],
}
dataset = pd.DataFrame(data)
dataset

     name  age
0   ahmed   33
1    john   54
2  faduma   18

In [55]:
print(dataset.shape)
print(dataset['age'].mean())
print(dataset['age'].max())
print(dataset['age'].std())

(3, 2)
35.0
54
18.083141320025124

In [56]:
dataset.describe()

             age
count   3.000000
mean   35.000000
std    18.083141
min    18.000000
25%    25.500000
50%    33.000000
75%    43.500000
max    54.000000

In [57]:
dataset[dataset['age'] > 20] # conditional select

    name  age
0  ahmed   33
1   john   54

In [58]:
df = pd.read_csv('weather.csv')
df.head(2)

         date       city  temperature_c  humidity wind_speed  rainfall_mm
0  2026-01-01  Mogadishu           31.0      75.0         12          0.0
1  2026-01-02  Mogadishu           32.0      78.0        NaN          0.0

In [59]:
df.tail(3)

         date       city  temperature_c  humidity wind_speed  rainfall_mm
7  2026-01-08     Afgoye            NaN      79.0         11          0.0
8  2026-01-09     Balcad           30.0      76.0         10          NaN
9  2026-01-10  Mogadishu           29.0      74.0          9          0.0

In [60]:
df['temperature_c'].max()

np.float64(35.0)

In [61]:
df[df['rainfall_mm'] > 0]

         date       city  temperature_c  humidity wind_speed  rainfall_mm
2  2026-01-03    Kismayo            NaN      80.0         15          1.0
5  2026-01-06  Mogadishu           33.0       NaN         13          2.0

In [62]:
df[df['humidity'] > df['humidity'].mean()]

         date       city  temperature_c  humidity wind_speed  rainfall_mm
2  2026-01-03    Kismayo            NaN      80.0         15          1.0
3  2026-01-04  Mogadishu           34.0      82.0         14          0.0
4  2026-01-05     Jowhar           35.0      85.0         16          0.0
7  2026-01-08     Afgoye            NaN      79.0         11          0.0

In [63]:
type(df['date'])

pandas.Series

In [64]:
df[df['date'] >= '2026-01-04']

         date       city  temperature_c  humidity wind_speed  rainfall_mm
3  2026-01-04  Mogadishu           34.0      82.0         14          0.0
4  2026-01-05     Jowhar           35.0      85.0         16          0.0
5  2026-01-06  Mogadishu           33.0       NaN         13          2.0
6  2026-01-07    Kismayo           31.0      77.0        abc          0.0
7  2026-01-08     Afgoye            NaN      79.0         11          0.0
8  2026-01-09     Balcad           30.0      76.0         10          NaN
9  2026-01-10  Mogadishu           29.0      74.0          9          0.0

In [65]:
df[df['city'] == 'Kismayo']

         date     city  temperature_c  humidity wind_speed  rainfall_mm
2  2026-01-03  Kismayo            NaN      80.0         15          1.0
6  2026-01-07  Kismayo           31.0      77.0        abc          0.0

In [66]:
df[df['wind_speed'] > df['wind_speed'].min()]

         date       city  temperature_c  humidity wind_speed  rainfall_mm
0  2026-01-01  Mogadishu           31.0      75.0         12          0.0
2  2026-01-03    Kismayo            NaN      80.0         15          1.0
3  2026-01-04  Mogadishu           34.0      82.0         14          0.0
4  2026-01-05     Jowhar           35.0      85.0         16          0.0
5  2026-01-06  Mogadishu           33.0       NaN         13          2.0
6  2026-01-07    Kismayo           31.0      77.0        abc          0.0
7  2026-01-08     Afgoye            NaN      79.0         11          0.0
9  2026-01-10  Mogadishu           29.0      74.0          9          0.0

# Conditional selection
- condition_mask is the where condition like in sql
- columns is like select with specified columns in sql
- in sql mind looks like  select date,city,temperature_c from df where temperature_c > 22
- what about * all columns just remove columns

In [67]:
condition_mask = df['temperature_c'] > 22
columns = ['date','city','temperature_c']
print(df[condition_mask])
df[columns][condition_mask]

         date       city  temperature_c  humidity wind_speed  rainfall_mm
0  2026-01-01  Mogadishu           31.0      75.0         12          0.0
1  2026-01-02  Mogadishu           32.0      78.0        NaN          0.0
3  2026-01-04  Mogadishu           34.0      82.0         14          0.0
4  2026-01-05     Jowhar           35.0      85.0         16          0.0
5  2026-01-06  Mogadishu           33.0       NaN         13          2.0
6  2026-01-07    Kismayo           31.0      77.0        abc          0.0
8  2026-01-09     Balcad           30.0      76.0         10          NaN
9  2026-01-10  Mogadishu           29.0      74.0          9          0.0

         date       city  temperature_c
0  2026-01-01  Mogadishu           31.0
1  2026-01-02  Mogadishu           32.0
3  2026-01-04  Mogadishu           34.0
4  2026-01-05     Jowhar           35.0
5  2026-01-06  Mogadishu           33.0
6  2026-01-07    Kismayo           31.0
8  2026-01-09     Balcad           30.0
9  2026-01-10  Mogadishu           29.0

In [68]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [69]:
df.set_index('date',inplace=True)

In [70]:
df

                 city  temperature_c  humidity wind_speed  rainfall_mm
date
2026-01-01  Mogadishu           31.0      75.0         12          0.0
2026-01-02  Mogadishu           32.0      78.0        NaN          0.0
2026-01-03    Kismayo            NaN      80.0         15          1.0
2026-01-04  Mogadishu           34.0      82.0         14          0.0
2026-01-05     Jowhar           35.0      85.0         16          0.0
2026-01-06  Mogadishu           33.0       NaN         13          2.0
2026-01-07    Kismayo           31.0      77.0        abc          0.0
2026-01-08     Afgoye            NaN      79.0         11          0.0
2026-01-09     Balcad           30.0      76.0         10          NaN
2026-01-10  Mogadishu           29.0      74.0          9          0.0

In [71]:
df.loc['2026-01-01']

city             Mogadishu
temperature_c         31.0
humidity              75.0
wind_speed              12
rainfall_mm            0.0
Name: 2026-01-01, dtype: object

In [72]:
df.reset_index(inplace=True)

In [73]:
df

         date       city  temperature_c  humidity wind_speed  rainfall_mm
0  2026-01-01  Mogadishu           31.0      75.0         12          0.0
1  2026-01-02  Mogadishu           32.0      78.0        NaN          0.0
2  2026-01-03    Kismayo            NaN      80.0         15          1.0
3  2026-01-04  Mogadishu           34.0      82.0         14          0.0
4  2026-01-05     Jowhar           35.0      85.0         16          0.0
5  2026-01-06  Mogadishu           33.0       NaN         13          2.0
6  2026-01-07    Kismayo           31.0      77.0        abc          0.0
7  2026-01-08     Afgoye            NaN      79.0         11          0.0
8  2026-01-09     Balcad           30.0      76.0         10          NaN
9  2026-01-10  Mogadishu           29.0      74.0          9          0.0

In [74]:
df.loc[0]

date             2026-01-01
city              Mogadishu
temperature_c          31.0
humidity               75.0
wind_speed               12
rainfall_mm             0.0
Name: 0, dtype: object

In [75]:
df.loc[[1,2]]

         date       city  temperature_c  humidity wind_speed  rainfall_mm
1  2026-01-02  Mogadishu           32.0      78.0        NaN          0.0
2  2026-01-03    Kismayo            NaN      80.0         15          1.0

## Locating with Series and DataFrame using df.loc

In [76]:
# Series
df.loc[1]

date             2026-01-02
city              Mogadishu
temperature_c          32.0
humidity               78.0
wind_speed              NaN
rainfall_mm             0.0
Name: 1, dtype: object

In [77]:
# DataFrame
df.loc[[1,2]]

         date       city  temperature_c  humidity wind_speed  rainfall_mm
1  2026-01-02  Mogadishu           32.0      78.0        NaN          0.0
2  2026-01-03    Kismayo            NaN      80.0         15          1.0

# Ways to create DataFrame

In [78]:
# csv
df = pd.read_csv("weather.csv")
df

         date       city  temperature_c  humidity wind_speed  rainfall_mm
0  2026-01-01  Mogadishu           31.0      75.0         12          0.0
1  2026-01-02  Mogadishu           32.0      78.0        NaN          0.0
2  2026-01-03    Kismayo            NaN      80.0         15          1.0
3  2026-01-04  Mogadishu           34.0      82.0         14          0.0
4  2026-01-05     Jowhar           35.0      85.0         16          0.0
5  2026-01-06  Mogadishu           33.0       NaN         13          2.0
6  2026-01-07    Kismayo           31.0      77.0        abc          0.0
7  2026-01-08     Afgoye            NaN      79.0         11          0.0
8  2026-01-09     Balcad           30.0      76.0         10          NaN
9  2026-01-10  Mogadishu           29.0      74.0          9          0.0

In [79]:
# dictionary
weather_data = {
    "date":['2026-01-03','2025-10-23'],
    "city":["mogadishu","Kismayo"],
    "temperature":[31,28]
}

df = pd.DataFrame(weather_data)
df

         date       city  temperature
0  2026-01-03  mogadishu           31
1  2025-10-23    Kismayo           28

In [80]:
# tuple list
weather_data = {
    ('2026-01-08','mogadishu',29),
    ('2025-09-11','jowhar',28)
}

df = pd.DataFrame(weather_data,columns=['date','city','temperature'])
df

         date       city  temperature
0  2025-09-11     jowhar           28
1  2026-01-08  mogadishu           29

In [81]:
# dictionary list
weather_data = [
    {'city':'mogadishu','temperature':22},
    {'city':'london','temperature':18},
    {'city':'paris','temperature':23}
]

df = pd.DataFrame(weather_data)
df

        city  temperature
0  mogadishu           22
1     london           18
2      paris           23

In [84]:
# excel
df = pd.read_excel("weather.xlsx",sheet_name="Sheet1")
df

,Unnamed: 0,date,city,temperature_c,humidity,wind_speed,rainfall_mm
0,0,2026-01-01,Mogadishu,31.0,75.0,12,0.0
1,1,2026-01-02,Mogadishu,32.0,78.0,NaN,0.0
2,2,2026-01-03,Kismayo,NaN,80.0,15,1.0
3,3,2026-01-04,Mogadishu,34.0,82.0,14,0.0
4,4,2026-01-05,Jowhar,35.0,85.0,16,0.0
5,5,2026-01-06,Mogadishu,33.0,NaN,13,2.0
6,6,2026-01-07,Kismayo,31.0,77.0,abc,0.0
7,7,2026-01-08,Afgoye,NaN,79.0,11,0.0
8,8,2026-01-09,Balcad,30.0,76.0,10,NaN
9,9,2026-01-10,Mogadishu,29.0,74.0,9,0.0

In [88]:
# Json
df = pd.read_json("weather.json")
df

        city  temperature
0  mogadishu           27
1    kismayo           21
2     jowhar           29